# Generated by Django 5.2 on 2025-04-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at_project_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_list',
        ),
    ]
